# Generated by Django 2.1.1 on 2018-11-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zi', models.CharField(max_length=10, verbose_name='字')),
                ('x', models.CharField(max_length=1024, verbose_name='行书')),
                ('c', models.CharField(max_length=1024, verbose_name='草书')),
                ('k', models.CharField(max_length=1024, verbose_name='楷书')),
                ('l', models.CharField(max_length=1024, verbose_name='隶书')),
                ('z', models.CharField(max_length=1024, verbose_name='篆书')),
                ('g', models.CharField(max_length=1024, verbose_name='钢笔')),
                ('o', models.CharField(max_length=1024, verbose_name='其它')),
                ('count', models.IntegerField(verbose_name='更新次数')),
            ],
        ),
        migrations.CreateModel(
            name='zidetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zi', models.CharField(max_length=10, verbose_name='字')),
                ('zitype', models.CharField(max_length=10, verbose_name='字体')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('no', models.CharField(max_length=10, verbose_name='编号(非必填)')),
                ('path', models.FilePathField(verbose_name='文件路径')),
                ('url', models.URLField(verbose_name='网络地址')),
                ('binaryfile', models.BinaryField(verbose_name='二进制文件(先不用它)')),
                ('status', models.BooleanField(verbose_name='下载状态')),
            ],
        ),
    ]
